import type { Metadata } from "next";
import "./globals.css";
import { Vazirmatn } from "next/font/google";
import { Toaster } from "sonner";
import Header from "@/app/shared/components/Header";
import Footer from "@/app/shared/components/Footer";
import "leaflet/dist/leaflet.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const vazir = Vazirmatn({
  subsets: ["arabic"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`mx-auto ${vazir.className}`}>
        <Header/>
        {children}
        <Footer/>
        <Toaster richColors position="top-center" closeButton />
      </body>
    </html>
  );
}
